import { StyleSheet, Dimensions } from 'react-native';
import { STREAM_H } from '../../constants/live/config';

const { width } = Dimensions.get('window');

// ─── Stream HUD styles ────────────────────────────────────────────────────────
export const streamStyles = StyleSheet.create({
  hudRoot: { ...StyleSheet.absoluteFillObject, overflow: 'hidden' },
  vignette: { ...StyleSheet.absoluteFillObject },
  cameraNameText: {
    fontSize: 11, fontWeight: '600', color: 'rgba(14, 234, 54, 0.9)',
    backgroundColor: 'rgba(0,0,0,0.45)', paddingHorizontal: 8, paddingVertical: 3,
    borderRadius: 6, maxWidth: width * 0.4,
  },
  topLeft:     { position: 'absolute', top: 10, left: 12, flexDirection: 'row', alignItems: 'center', gap: 8 },
  topRight:    { position: 'absolute', top: 10, right: 12, alignItems: 'flex-end' },
  bottomLeft:  { position: 'absolute', bottom: 10, left: 12 },
  bottomRight: { position: 'absolute', bottom: 10, right: 12, alignItems: 'flex-end', gap: 4 },
  liveBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    backgroundColor: 'rgba(0,0,0,0.55)', paddingHorizontal: 8, paddingVertical: 3,
    borderRadius: 6, borderWidth: 0.5, borderColor: 'rgba(255,255,255,0.1)',
  },
  statusDotTiny: { width: 6, height: 6, borderRadius: 3 },
  liveText: { fontSize: 10, fontWeight: '700', color: 'rgba(255,255,255,0.85)', letterSpacing: 1 },
  clockText: {
    fontSize: 11, fontWeight: '600', color: 'rgba(255,255,255,0.7)',
    letterSpacing: 0.5, fontFamily: 'monospace' as any,
    backgroundColor: 'rgba(0,0,0,0.45)', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 5,
  },
  locationText: { fontSize: 10, color: 'rgba(255,255,255,0.45)', letterSpacing: 0.5 },
  detCountBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: 'rgba(0,0,0,0.55)', paddingHorizontal: 7, paddingVertical: 3,
    borderRadius: 5, borderWidth: 0.5,
  },
  detCountText: { fontSize: 9, fontWeight: '700', letterSpacing: 0.5, fontFamily: 'monospace' as any },
  zoneBadgeHud: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: 'rgba(0,0,0,0.55)', paddingHorizontal: 7, paddingVertical: 3,
    borderRadius: 5, borderWidth: 0.5, borderColor: 'rgba(255,149,0,0.4)',
  },
  zoneBadgeText: { fontSize: 9, fontWeight: '700', color: '#FF9500', letterSpacing: 0.5, fontFamily: 'monospace' as any },
  webrtcBadge: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: 'rgba(0,122,255,0.2)', paddingHorizontal: 7, paddingVertical: 3,
    borderRadius: 20, borderWidth: 0.5, borderColor: 'rgba(0,122,255,0.4)',
  },
  webrtcDot: { width: 5, height: 5, borderRadius: 3 },
  webrtcBadgeText: { fontSize: 9, fontWeight: '600', letterSpacing: 0.3 },
  detBox: { position: 'absolute', borderWidth: 0 },
  detCorner: { position: 'absolute', width: 10, height: 10 },
  detLabel: {
    position: 'absolute', top: -20, left: 0,
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 5, paddingVertical: 2, borderRadius: 3, gap: 4,
  },
  detLabelText: { fontSize: 9, fontWeight: '700', color: '#000', letterSpacing: 0.5, fontFamily: 'monospace' as any },
  detConfText:  { fontSize: 8, color: 'rgba(0,0,0,0.7)', fontFamily: 'monospace' as any },
});

// ─── Fullscreen styles ────────────────────────────────────────────────────────
export const fsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  videoArea: { flex: 1, overflow: 'hidden' },
  vignette:  { ...StyleSheet.absoluteFillObject },
  topBar: {
    position: 'absolute', top: 0, left: 0, right: 0,
    paddingTop: 52, paddingHorizontal: 20, paddingBottom: 14,
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderBottomWidth: 0.5, borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  fullscreenCameraName: {
    fontSize: 14, fontWeight: '600', color: 'rgba(0, 255, 13, 0.86)',
    backgroundColor: 'rgba(0,0,0,0.5)', paddingHorizontal: 10,
    paddingVertical: 4, borderRadius: 8, marginRight: 8,
  },
  topCenter: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10, marginLeft: 12 },
  topRight:  { alignItems: 'flex-end' },
  liveDot:   { width: 7, height: 7, borderRadius: 4, backgroundColor: '#FF3B30' },
  liveLabel: { fontSize: 10, fontWeight: '700', color: '#FF3B30', letterSpacing: 2 },
  locationLabel: { fontSize: 12, fontWeight: '500', color: 'rgba(255, 255, 255, 0.6)' },
  webrtcPill: {
    backgroundColor: 'rgba(0,122,255,0.2)', paddingHorizontal: 7, paddingVertical: 2,
    borderRadius: 20, borderWidth: 0.5, borderColor: 'rgba(0,122,255,0.4)',
  },
  webrtcPillText: { fontSize: 9, fontWeight: '600', color: '#60AAFF', letterSpacing: 0.3 },
  bottomBar: {
    position: 'absolute', bottom: 0, left: 0, right: 0,
    paddingBottom: 36, paddingTop: 14, paddingHorizontal: 20,
    backgroundColor: 'rgba(0,0,0,0.65)',
    borderTopWidth: 0.5, borderTopColor: 'rgba(255,255,255,0.08)', gap: 14,
  },
  toolRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 4 },
  toolBtn: {
    flex: 1, alignItems: 'center', justifyContent: 'center',
    gap: 4, paddingVertical: 8, borderRadius: 8,
    backgroundColor: 'transparent', borderWidth: 0, borderColor: 'transparent',
  },
  toolLabel: { fontSize: 9, color: 'rgba(255,255,255,0.55)', fontWeight: '600', letterSpacing: 0.3 },
  toolBtnGreen: { backgroundColor: 'rgba(52,199,89,0.12)', borderColor: 'rgba(52,199,89,0.3)' },
  toolBtnRec:   { backgroundColor: 'rgba(255,59,48,0.15)', borderColor: 'rgba(255,59,48,0.35)' },
  iconBtn: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: 'transparent', alignItems: 'center', justifyContent: 'center',
  },
  recBar: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    backgroundColor: 'rgba(36, 2, 0, 0)', borderRadius: 8,
    paddingHorizontal: 12, paddingVertical: 7,
    borderWidth: 0.5, borderColor: 'rgba(255,59,48,0.3)',
  },
  recBarDot:  { width: 7, height: 7, borderRadius: 4, backgroundColor: '#FF3B30' },
  recBarText: { fontSize: 11, color: 'rgba(255,255,255,0.7)', fontWeight: '600' },
});

// ─── Main screen styles ───────────────────────────────────────────────────────
export const styles = StyleSheet.create({
  container:        { flex: 1, backgroundColor: '#F2F2F7', paddingBottom: 30 },
  scrollContent:    { paddingBottom: 32 },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, backgroundColor: '#F2F2F7' },
  loadingText:      { fontSize: 14, color: '#AEAEB2' },
  emptyText:        { fontSize: 16, fontWeight: '600', color: '#AEAEB2', marginTop: 8 },
  retryBtn:         { marginTop: 8, paddingHorizontal: 24, paddingVertical: 10, backgroundColor: '#007AFF', borderRadius: 20 },
  retryText:        { color: '#fff', fontWeight: '700', fontSize: 14 },
  noCamsBox:        { marginHorizontal: 16, marginBottom: 16, padding: 20, backgroundColor: '#fff', borderRadius: 14, alignItems: 'center' },
  noCamsText:       { color: '#AEAEB2', fontSize: 13 },
  go2rtcWarning:    { flexDirection: 'row', alignItems: 'flex-start', gap: 8, marginHorizontal: 16, marginBottom: 10, backgroundColor: '#FFF8E1', borderRadius: 10, padding: 10, borderWidth: 0.5, borderColor: '#FF9500' },
  go2rtcWarningText:{ flex: 1, fontSize: 12, color: '#7A5000' },
  streamCard:       { marginHorizontal: 16, borderRadius: 20, overflow: 'hidden', backgroundColor: '#0C0C0E', marginBottom: 4 },
  streamPlaceholder:{ height: STREAM_H, overflow: 'hidden' },
  recTimerPill:     { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: 'rgba(255,59,48,0.85)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 5 },
  recDot:           { width: 6, height: 6, borderRadius: 3, backgroundColor: '#fff' },
  recTimerText:     { fontSize: 11, fontWeight: '700', color: '#fff', letterSpacing: 0.5, fontFamily: 'monospace' as any },
  streamFooter:     { paddingHorizontal: 14, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: '#111318' },
  camSub:           { fontSize: 11, color: 'rgba(255,255,255,0.35)', marginTop: 2 },
  streamActions:    { flexDirection: 'row', gap: 6, alignItems: 'center' },
  actionBtn: {
    width: 34, height: 34, borderRadius: 8,
    backgroundColor: 'transparent', alignItems: 'center', justifyContent: 'center',
  },
  actionBtnActive: { backgroundColor: 'rgba(52,199,89,0.15)' },
  videoToolsRow: {
    flexDirection: 'row', gap: 2, paddingHorizontal: 14,
    paddingBottom: 10, paddingTop: 2, backgroundColor: '#111318',
  },
  videoToolBtn: {
    flex: 1, alignItems: 'center', justifyContent: 'center',
    gap: 3, paddingVertical: 6, borderRadius: 8,
    backgroundColor: 'transparent',
  },
  videoToolLabel:   { fontSize: 9, color: 'rgba(255,255,255,0.45)', fontWeight: '500' },
  videoToolBtnGreen:{ backgroundColor: 'rgba(52,199,89,0.12)' },
  videoToolBtnRec:  { backgroundColor: 'rgba(255,59,48,0.15)' },
  zoneModeBar:      { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 7 },
  zoneModeText:     { fontSize: 11, color: '#fff', fontWeight: '600', flex: 1 },
  zoneDeleteBtn:    { position: 'absolute', top: 0, right: 0, zIndex: 30, width: 20, height: 20, borderRadius: 10, backgroundColor: '#FF3B30', alignItems: 'center', justifyContent: 'center', elevation: 5 },
  cornerHandle:     { position: 'absolute', width: 20, height: 20, borderRadius: 5, backgroundColor: '#FF3B30', alignItems: 'center', justifyContent: 'center', zIndex: 20, elevation: 5 },
  drawHintOverlay:  { alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: 'rgba(0,0,0,0.2)' },
  drawHintText:     { fontSize: 12, fontWeight: '700', color: 'rgba(255,255,255,0.7)' },
  draftLabel:       { position: 'absolute', top: 4, left: 4, backgroundColor: '#FF9500', paddingHorizontal: 5, paddingVertical: 2, borderRadius: 3 },
  draftLabelText:   { fontSize: 9, color: '#fff', fontWeight: '700', fontFamily: 'monospace' as any },
  sectionHeader:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, marginBottom: 12, marginTop: 20 },
  sectionTitle:     { fontSize: 16, fontWeight: '700', color: '#1C1C1E' },
  sectionHint:      { fontSize: 12, color: '#AEAEB2' },
  recCountBadge:    { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#FF3B3015', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(255,59,48,0.25)' },
  recCountDot:      { width: 6, height: 6, borderRadius: 3, backgroundColor: '#FF3B30' },
  recCountText:     { fontSize: 11, fontWeight: '700', color: '#FF3B30' },
  camScroll:        { paddingLeft: 16, marginBottom: 24 },
  camThumb:         { width: 130, marginRight: 10, borderRadius: 14, overflow: 'hidden', borderWidth: 2, borderColor: 'transparent' },
  camThumbActive:   { borderColor: '#007AFF' },
  camThumbImg:      { height: 80, backgroundColor: '#1C1C1E', alignItems: 'center', justifyContent: 'center' },
  camThumbFooter:   { backgroundColor: '#111', padding: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  camThumbName:     { fontSize: 11, fontWeight: '600', color: '#fff', flex: 1 },
  statusDotSm:      { width: 5, height: 5, borderRadius: 3 },
  camRecBadge:      { position: 'absolute', top: 6, right: 6, width: 10, height: 10, borderRadius: 5, backgroundColor: '#ff3a3000', borderWidth: 1.5, borderColor: '#1C1C1E' },
  sensorsGrid:      { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: 16, gap: 12, marginBottom: 16 },
  sensorCard:       { width: (width - 44) / 2, backgroundColor: '#fff', borderRadius: 18, padding: 14, borderWidth: 0.5, borderColor: 'rgba(0,0,0,0.06)' },
  sensorIconBg:     { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  sensorLabel:      { fontSize: 11, color: '#AEAEB2', fontWeight: '500', marginBottom: 2 },
  sensorValue:      { fontSize: 20, fontWeight: '700', color: '#1C1C1E' },
  sensorUnit:       { fontSize: 12, fontWeight: '500', color: '#AEAEB2' },
  sensorStatus:     { fontSize: 10, fontWeight: '700', marginTop: 4 },
  sensorBarTrack:   { height: 3, borderRadius: 2, backgroundColor: 'rgba(0,0,0,0.06)', marginTop: 8, overflow: 'hidden' },
  sensorBarFill:    { height: 3, borderRadius: 2 },
  blockedAlert:     { position: 'absolute', top: 0, left: 0, right: 0, paddingHorizontal: 16, paddingTop: 12, zIndex: 999 },
  blockedAlertInner:{ backgroundColor: '#FFF0F0', borderRadius: 16, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: '#FF3B30', elevation: 8 },
  blockedAlertIcon: { width: 44, height: 44, borderRadius: 12, backgroundColor: '#FFE5E5', alignItems: 'center', justifyContent: 'center' },
  blockedAlertTitle:{ fontSize: 14, fontWeight: '800', color: '#FF3B30' },
  blockedAlertSub:  { fontSize: 11, color: '#8E3030', marginTop: 2 },
  overlay:          { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  sheet:            { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingTop: 12, maxHeight: '85%' },
  sheetHandle:      { width: 36, height: 4, borderRadius: 2, backgroundColor: 'rgba(0,0,0,0.12)', alignSelf: 'center', marginBottom: 16 },
  closeBtn:         { width: 32, height: 32, borderRadius: 16, backgroundColor: '#F2F2F7', alignItems: 'center', justifyContent: 'center' },
  sheetTitle:       { fontSize: 16, fontWeight: '700', color: '#1C1C1E' },
  sheetSub:         { fontSize: 12, color: '#AEAEB2', marginTop: 1 },
  sheetTitle2:      { fontSize: 16, fontWeight: '700', color: '#1C1C1E', marginBottom: 2 },
  sheetSub2:        { fontSize: 12, color: '#AEAEB2', marginBottom: 16 },
  optionsCard:      { backgroundColor: '#F9F9F9', borderRadius: 16, overflow: 'hidden' },
  optionRow:        { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12, gap: 12 },
  optionRowBorder:  { borderBottomWidth: 0.5, borderBottomColor: 'rgba(0,0,0,0.06)' },
  optionIconBg:     { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  optionLabel:      { fontSize: 14, fontWeight: '600', color: '#1C1C1E' },
  optionSub:        { fontSize: 11, color: '#AEAEB2', marginTop: 1 },
  detailHeader:     { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 20 },
  detailIconBg:     { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  bigValueCard:     { backgroundColor: '#F9F9F9', borderRadius: 16, padding: 20, marginBottom: 12, alignItems: 'center' },
  bigValue:         { fontSize: 48, fontWeight: '700', color: '#1C1C1E' },
  bigUnit:          { fontSize: 20, fontWeight: '500', color: '#AEAEB2' },
  progressTrack:    { height: 6, borderRadius: 3, backgroundColor: 'rgba(0,0,0,0.07)', width: '100%', marginTop: 16, overflow: 'hidden' },
  progressFill:     { height: 6, borderRadius: 3 },
  progressLabels:   { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginTop: 4 },
  progressLbl:      { fontSize: 10, color: '#AEAEB2' },
  detailCard:       { backgroundColor: '#F9F9F9', borderRadius: 16, padding: 16, marginBottom: 12 },
  detailCardTitle:  { fontSize: 12, fontWeight: '600', color: '#AEAEB2', marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.5 },
  sparkLabels:      { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  sparkLbl:         { fontSize: 10, color: '#AEAEB2', flex: 1, textAlign: 'center' },
  statsGrid:        { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 12 },
  statCard:         { flex: 1, minWidth: '45%', backgroundColor: '#F9F9F9', borderRadius: 12, padding: 12 },
  statLabel:        { fontSize: 11, color: '#AEAEB2', marginBottom: 4 },
  statValue:        { fontSize: 15, fontWeight: '700', color: '#1C1C1E' },
  descCard:         { flexDirection: 'row', gap: 10, backgroundColor: '#EAF4FF', borderRadius: 14, padding: 14, marginBottom: 12, alignItems: 'flex-start' },
  descText:         { flex: 1, fontSize: 13, color: '#004A8F', lineHeight: 19 },
  threshRow:        { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 6 },
  threshDot:        { width: 8, height: 8, borderRadius: 4 },
  threshLabel:      { fontSize: 13, color: '#1C1C1E', flex: 1 },
  threshVal:        { fontSize: 12, color: '#AEAEB2' },
});