import { StyleSheet, Platform } from 'react-native';

export const SS = StyleSheet.create({
  overlay:  { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  sheet:    { backgroundColor: '#1C1C1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 40, paddingHorizontal: 20, paddingTop: 12 },
  handle:   { width: 36, height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.2)', alignSelf: 'center', marginBottom: 16 },
  heading:  { fontSize: 13, fontWeight: '700', color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 1, textAlign: 'center', marginBottom: 8 },
  row:      { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(255,255,255,0.08)' },
  rowTxt:   { fontSize: 17, color: 'rgba(255,255,255,0.7)', fontWeight: '500' },
  rowTxtOn: { color: '#FF3B30', fontWeight: '700' },
});

export const P = StyleSheet.create({
  nativeContainer: { flex: 1, backgroundColor: '#09090B', justifyContent: 'center', alignItems: 'center' },
  nativeHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, position: 'absolute', top: 0, left: 0, right: 0, zIndex: 10, backgroundColor: 'rgba(9, 9, 11, 0.85)', paddingBottom: 12 },
  nativeTitle: { fontSize: 16, fontWeight: '700', color: '#FAFAFA' },
  nativeSub: { fontSize: 11, color: '#71717A', marginTop: 2, fontFamily: 'monospace' },
  nativeCloseBtn: { padding: 2 },
  videoWrapper: { width: '100%', aspectRatio: 16 / 9, backgroundColor: '#000' },
  nativeMetaRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, position: 'absolute', bottom: 0, left: 0, right: 0, alignItems: 'center', backgroundColor: 'rgba(9, 9, 11, 0.6)', paddingTop: 12 },
  metaChip: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#18181B', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14, borderWidth: 1, borderColor: '#27272A' },
  metaChipTxt: { fontSize: 12, color: '#E4E4E7', fontWeight: '600' },
  portraitClosePill: { backgroundColor: '#FF3B30', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 14 },
  portraitClosePillTxt: { color: '#fff', fontSize: 12, fontWeight: '700' },
});

export const S = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F2F7',paddingBottom:16 },
  centered:  { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, backgroundColor: '#F2F2F7' },
  loadTxt:   { fontSize: 14, color: '#AEAEB2' },
  selector:    { backgroundColor: '#fff', paddingTop: Platform.OS === 'ios' ? 56 : 36, paddingBottom: 16, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: 'rgba(0,0,0,0.1)', shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 4, elevation: 2 },
  selectorLbl: { fontSize: 11, fontWeight: '700', color: '#AEAEB2', textTransform: 'uppercase', letterSpacing: 0.5, paddingHorizontal: 16, marginBottom: 10 },
  selectorRow: { paddingHorizontal: 16, gap: 8 },
  chip:          { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 9, borderRadius: 20, backgroundColor: '#F2F2F7', borderWidth: 0.5, borderColor: 'rgba(0,0,0,0.08)' },
  chipOn:        { backgroundColor: '#1C1C1E', borderColor: '#1C1C1E' },
  chipDot:       { width: 6, height: 6, borderRadius: 3 },
  chipTxt:       { fontSize: 13, fontWeight: '600', color: '#AEAEB2' },
  chipTxtOn:     { color: '#fff' },
  chipBadge:     { backgroundColor: 'rgba(0,0,0,0.08)', borderRadius: 10, paddingHorizontal: 6, paddingVertical: 1 },
  chipBadgeOn:   { backgroundColor: 'rgba(255,255,255,0.2)' },
  chipBadgeTxt:  { fontSize: 10, fontWeight: '700', color: '#AEAEB2' },
  chipBadgeTxtOn:{ color: '#fff' },
  list:      { paddingHorizontal: 16, paddingTop:16 ,marginBottom:50 },
  listEmpty: { flex: 1, justifyContent: 'center' },
  errBanner: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FFF0EE', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 10, marginBottom: 16, borderWidth: 0.5, borderColor: '#FECACA' },
  errTxt:    { fontSize: 13, color: '#FF3B30', flex: 1 },
  emptyState: { alignItems: 'center', paddingVertical: 48 },
  emptyIcon:  { width: 80, height: 80, borderRadius: 24, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', marginBottom: 16, borderWidth: 0.5, borderColor: 'rgba(0,0,0,0.07)' },
  emptyTitle: { fontSize: 16, fontWeight: '600', color: '#AEAEB2', marginTop: 8 },
  emptySub:   { fontSize: 13, color: '#C7C7CC', textAlign: 'center', marginTop: 4 },
  card:        { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#fff', borderRadius: 16, paddingHorizontal: 14, paddingVertical: 14, marginBottom: 10, borderWidth: 0.5, borderColor: 'rgba(0,0,0,0.06)', shadowColor: '#000', shadowOpacity: 0.03, shadowRadius: 6, shadowOffset: { width: 0, height: 2 }, elevation: 1 },
  cardThumb:   { width: 46, height: 46, borderRadius: 14, backgroundColor: '#FF3B3010', alignItems: 'center', justifyContent: 'center' },
  cardBody:    { flex: 1 },
  cardTop:     { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  cardTitle:   { fontSize: 15, fontWeight: '700', color: '#1C1C1E', flex: 1 },
  cardPill:    { backgroundColor: '#FF3B3012', paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6 },
  cardPillTxt: { fontSize: 9, fontWeight: '800', letterSpacing: 0.5, color: '#FF3B30' },
  cardMeta:    { flexDirection: 'row', alignItems: 'center', gap: 4, flexWrap: 'wrap' },
  cardMetaTxt: { fontSize: 11, color: '#AEAEB2' },
  dot:         { fontSize: 11, color: '#C7C7CC' },
  playBtn:     { width: 38, height: 38, borderRadius: 19, backgroundColor: '#FF3B30', alignItems: 'center', justifyContent: 'center', shadowColor: '#FF3B30', shadowOpacity: 0.35, shadowRadius: 8, shadowOffset: { width: 0, height: 3 } },
});